//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace about_res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaserSoftwareWebMVCv2.Resources.AboutPage", typeof(AboutPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015 yılında kurulan Başer Yazılım insanları yazılım dünyasında geleceğe taşımak amacı ile kurulmuştur..
        /// </summary>
        public static string Hakkimizda_Aciklama {
            get {
                return ResourceManager.GetString("Hakkimizda_Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oğuzhan Başer tarafından kurulan Başer Yazılım ilk başlarda sadece fikirden ibaretti..
        /// </summary>
        public static string Hakkimizda_Aciklama2 {
            get {
                return ResourceManager.GetString("Hakkimizda_Aciklama2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mart 2015 tarihinde fikir olmaktan çıkıp aktif olmuştur..
        /// </summary>
        public static string Hakkimizda_Aciklama3 {
            get {
                return ResourceManager.GetString("Hakkimizda_Aciklama3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 ay boyunca hazırlık süreci yaşayan Başer Yazılım, Ağustos 2015 tarihinde Pixel Run Android Oyun Projesi ile piyasaya açılmıştır..
        /// </summary>
        public static string Hakkimizda_Aciklama4 {
            get {
                return ResourceManager.GetString("Hakkimizda_Aciklama4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzun süre boyunca proje yürütmekte başarılı olamamıştır..
        /// </summary>
        public static string Hakkimizda_Aciklama5 {
            get {
                return ResourceManager.GetString("Hakkimizda_Aciklama5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temmuz 2016 tarihine kadar hiçbir proje çalışması gerçekleştirmemiştir..
        /// </summary>
        public static string Hakkimizda_Aciklama6 {
            get {
                return ResourceManager.GetString("Hakkimizda_Aciklama6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şuan Download Time Calculator Win10 Edition,Download Time Calculator Android Edition,Apk Manager,DeathMatch projelerini yürütmektedir..
        /// </summary>
        public static string Hakkimizda_Aciklama7 {
            get {
                return ResourceManager.GetString("Hakkimizda_Aciklama7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube üzerinden Yazılım ve Teknoloji videoları paylaşmaktadır..
        /// </summary>
        public static string Hakkimizda_Aciklama8 {
            get {
                return ResourceManager.GetString("Hakkimizda_Aciklama8", resourceCulture);
            }
        }
    }
}
