//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace homePage_res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaserSoftwareWebMVCv2.Resources.HomePage", typeof(HomePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başer Yazılım&apos;a Hoşgeldiniz.
        /// </summary>
        public static string BaserYazilima_Hosgeldiniz {
            get {
                return ResourceManager.GetString("BaserYazilima_Hosgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byTR Yama App Discord Kanalımız.
        /// </summary>
        public static string byTR_Yama_Discord {
            get {
                return ResourceManager.GetString("byTR_Yama_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başer Yazılım insanlar için en iyisine ulaşmak için kurulmuştur..Başer Yazılım sayesin de geleceğin teknolojisi hakkında bilmediğiniz kalmayacak.Geleceğe odaklı projelerimiz sayesinde sizlerde gündemi takip edebileceksiniz...
        /// </summary>
        public static string Content_Aciklama {
            get {
                return ResourceManager.GetString("Content_Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmet Bulunamadı.
        /// </summary>
        public static string Hizmet_Bulunamadi {
            get {
                return ResourceManager.GetString("Hizmet_Bulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetlerimiz.
        /// </summary>
        public static string Hizmetlerimiz {
            get {
                return ResourceManager.GetString("Hizmetlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her Kitleye Uygun Çözüm Yolları Bizde.
        /// </summary>
        public static string Madde_1 {
            get {
                return ResourceManager.GetString("Madde_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenmenin En Kolay Yolu Bizde.
        /// </summary>
        public static string Madde_2 {
            get {
                return ResourceManager.GetString("Madde_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeteneğini Kullanarak Kazanmanın Yolları Bizde.
        /// </summary>
        public static string Madde_3 {
            get {
                return ResourceManager.GetString("Madde_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her bütçeye uygun çözüm yolları bizde.
        /// </summary>
        public static string Madde_4 {
            get {
                return ResourceManager.GetString("Madde_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazılım,bilgisayar,teknoloji gibi alanlara ilgi duyuyorsan seni de aramızda görmekten mutluluk duyarız.Bizimle beraber bilgilerini arttırırken kazanmanın yollarını keşfet..
        /// </summary>
        public static string Madde_Aciklama {
            get {
                return ResourceManager.GetString("Madde_Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neden Başer Yazılım.
        /// </summary>
        public static string Neden_Baser_Yazilim {
            get {
                return ResourceManager.GetString("Neden_Baser_Yazilim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politika Sayfası.
        /// </summary>
        public static string politika_sayfasi {
            get {
                return ResourceManager.GetString("politika_sayfasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeler.
        /// </summary>
        public static string Projeler {
            get {
                return ResourceManager.GetString("Projeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümünü Göster.
        /// </summary>
        public static string Tümünü_Goster {
            get {
                return ResourceManager.GetString("Tümünü_Goster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenilik Haberleri.
        /// </summary>
        public static string Yenilik_Haberleri {
            get {
                return ResourceManager.GetString("Yenilik_Haberleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projelerimiz sayfasında düzenlemeler yapıldı..
        /// </summary>
        public static string yenilik1 {
            get {
                return ResourceManager.GetString("yenilik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projelerimiz Sayfasında Header ve Footer çalışmama sorunu düzeltildi..
        /// </summary>
        public static string yenilik2 {
            get {
                return ResourceManager.GetString("yenilik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byDock Uygulama Bilgileri Eklendi..
        /// </summary>
        public static string yenilik3 {
            get {
                return ResourceManager.GetString("yenilik3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Time Calculator Uygulama Bilgileri Güncellendi..
        /// </summary>
        public static string yenilik4 {
            get {
                return ResourceManager.GetString("yenilik4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Sunucularımızın Widget&apos;ı Eklendi..
        /// </summary>
        public static string yenilik5 {
            get {
                return ResourceManager.GetString("yenilik5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Dil Desteği Eklendi..
        /// </summary>
        public static string yenilik6 {
            get {
                return ResourceManager.GetString("yenilik6", resourceCulture);
            }
        }
    }
}
