//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latestNews {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LatestNewsPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LatestNewsPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaserSoftwareWebMVCv2.Resources.LatestNewsPage", typeof(LatestNewsPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağustos.
        /// </summary>
        public static string Agustos {
            get {
                return ResourceManager.GetString("Agustos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aralık.
        /// </summary>
        public static string Aralik {
            get {
                return ResourceManager.GetString("Aralik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekim.
        /// </summary>
        public static string Ekim {
            get {
                return ResourceManager.GetString("Ekim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eylül.
        /// </summary>
        public static string Eylul {
            get {
                return ResourceManager.GetString("Eylul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haziran.
        /// </summary>
        public static string Haziran {
            get {
                return ResourceManager.GetString("Haziran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasım.
        /// </summary>
        public static string Kasim {
            get {
                return ResourceManager.GetString("Kasim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mart.
        /// </summary>
        public static string Mart {
            get {
                return ResourceManager.GetString("Mart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayıs.
        /// </summary>
        public static string Mayıs {
            get {
                return ResourceManager.GetString("Mayıs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nisan.
        /// </summary>
        public static string Nisan {
            get {
                return ResourceManager.GetString("Nisan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocak.
        /// </summary>
        public static string Ocak {
            get {
                return ResourceManager.GetString("Ocak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubat.
        /// </summary>
        public static string Subat {
            get {
                return ResourceManager.GetString("Subat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temmuz.
        /// </summary>
        public static string Temmuz {
            get {
                return ResourceManager.GetString("Temmuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Yenilikler.
        /// </summary>
        public static string Tüm_Yenilikler {
            get {
                return ResourceManager.GetString("Tüm_Yenilikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Store Mağazamız da ürün satışlarına başlandı..
        /// </summary>
        public static string v1_0_1 {
            get {
                return ResourceManager.GetString("v1.0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir çok alt yapı sorunu düzeltildi..
        /// </summary>
        public static string v1_0_2 {
            get {
                return ResourceManager.GetString("v1.0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Store Mağazamız&apos;a yeni ürün eklendi..
        /// </summary>
        public static string v1_0_2_1 {
            get {
                return ResourceManager.GetString("v1.0.2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzeltmeler Yapıldı..
        /// </summary>
        public static string v1_0_2_2 {
            get {
                return ResourceManager.GetString("v1.0.2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp&apos;dan Mesaj Gönderme Özelliği Eklendi..
        /// </summary>
        public static string v1_0_3 {
            get {
                return ResourceManager.GetString("v1.0_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizasyon Yapıldı..
        /// </summary>
        public static string v1_0_4 {
            get {
                return ResourceManager.GetString("v1.0_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık Düzeltmeleri Yapıldı..
        /// </summary>
        public static string v1_0_5 {
            get {
                return ResourceManager.GetString("v1.0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Sitemiz de yaşanan erişim sorunu düzeltildi..
        /// </summary>
        public static string v1_5_1_1 {
            get {
                return ResourceManager.GetString("v1.5.1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik Sistemi Kaldırıldı..
        /// </summary>
        public static string v1_5_1_2 {
            get {
                return ResourceManager.GetString("v1.5.1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows ChangeLog Center Uygulama Bilgileri Eklendi..
        /// </summary>
        public static string v1_5_1_3 {
            get {
                return ResourceManager.GetString("v1.5.1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Time Calculator Uygulama Bilgileri Eklendi..
        /// </summary>
        public static string v1_5_1_4 {
            get {
                return ResourceManager.GetString("v1.5.1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apk Manager Uygulama Bilgileri Güncellendi..
        /// </summary>
        public static string v1_5_1_5 {
            get {
                return ResourceManager.GetString("v1.5.1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canlı Destek Özelliği Eklendi..
        /// </summary>
        public static string v1_5_1_6 {
            get {
                return ResourceManager.GetString("v1.5.1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVC 5 sürümüne güncellendi..
        /// </summary>
        public static string v1_7_1 {
            get {
                return ResourceManager.GetString("v1.7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaynak Kodlar Güncellendi..
        /// </summary>
        public static string v1_7_2 {
            get {
                return ResourceManager.GetString("v1.7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Sitesinde ki gecikmeler düzeltildi..
        /// </summary>
        public static string v1_7_3 {
            get {
                return ResourceManager.GetString("v1.7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altyapı Güncellendi..
        /// </summary>
        public static string v1_7_4 {
            get {
                return ResourceManager.GetString("v1.7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Time Calculator Win10 Edition Bilgileri Eklendi..
        /// </summary>
        public static string v1_7_5 {
            get {
                return ResourceManager.GetString("v1.7_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politika Sayfası MVC sürümüne uyarlandı..
        /// </summary>
        public static string v2_0 {
            get {
                return ResourceManager.GetString("v2.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apk Manager Hakkında ki bilgiler Güncellendi..
        /// </summary>
        public static string v2_0_2 {
            get {
                return ResourceManager.GetString("v2.0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Time Calculator Uygulama Bilgileri Eklendi..
        /// </summary>
        public static string v2_0_3 {
            get {
                return ResourceManager.GetString("v2.0_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to policy.basersoftware.com üzerinden politika sayfasına ulaşabilirsiniz..
        /// </summary>
        public static string v2_0_4 {
            get {
                return ResourceManager.GetString("v2.0_4", resourceCulture);
            }
        }
    }
}
