//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace layout_res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaserSoftwareWebMVCv2.Resources.layout", typeof(layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string Ana_Sayfa {
            get {
                return ResourceManager.GetString("Ana_Sayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Saatlerimiz.
        /// </summary>
        public static string Calisma_Saatlerimiz {
            get {
                return ResourceManager.GetString("Calisma_Saatlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çarşamba.
        /// </summary>
        public static string Carsamba {
            get {
                return ResourceManager.GetString("Carsamba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuma.
        /// </summary>
        public static string Cuma {
            get {
                return ResourceManager.GetString("Cuma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumartesi.
        /// </summary>
        public static string Cumartesi {
            get {
                return ResourceManager.GetString("Cumartesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Sunucularımız.
        /// </summary>
        public static string discord_sunucularımız {
            get {
                return ResourceManager.GetString("discord_sunucularımız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politika Yükleniyor....
        /// </summary>
        public static string LoadingPolicy {
            get {
                return ResourceManager.GetString("LoadingPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pazartesi.
        /// </summary>
        public static string Pazartesi {
            get {
                return ResourceManager.GetString("Pazartesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perşembe.
        /// </summary>
        public static string Persembe {
            get {
                return ResourceManager.GetString("Persembe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politika Sayfası.
        /// </summary>
        public static string politika_sayfasi {
            get {
                return ResourceManager.GetString("politika_sayfasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projelerimiz.
        /// </summary>
        public static string Projelerimiz {
            get {
                return ResourceManager.GetString("Projelerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salı.
        /// </summary>
        public static string Sali {
            get {
                return ResourceManager.GetString("Sali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Hesaplar.
        /// </summary>
        public static string Sosyal_Hesaplar {
            get {
                return ResourceManager.GetString("Sosyal_Hesaplar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon:.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp&apos;dan Mesaj Gönder.
        /// </summary>
        public static string Whatsappdan_Mesaj_Gonder {
            get {
                return ResourceManager.GetString("Whatsappdan_Mesaj_Gonder", resourceCulture);
            }
        }
    }
}
